# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-29 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20161129_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='memu',
            name='url',
            field=models.URLField(default='#'),
        ),
    ]
