# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-29 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_memu_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Memu',
            new_name='Menu',
        ),
    ]
