# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-29 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20161129_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
