# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-29 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20161129_2239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['id'], 'verbose_name': '生成菜单', 'verbose_name_plural': '菜单别名'},
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='菜单名'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.URLField(default='#', verbose_name='菜单连接'),
        ),
    ]
