# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-29 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20161130_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='images',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
