# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-30 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_menu_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='产品名称')),
                ('reduce', models.TextField(verbose_name='产品介绍')),
                ('url', models.URLField(max_length=50, verbose_name='产品链接')),
                ('img', models.ImageField(null=True, upload_to='products', verbose_name='产品图片')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品编辑',
            },
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['id'], 'verbose_name': '菜单生成', 'verbose_name_plural': '菜单编辑'},
        ),
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.URLField(default='#', verbose_name='菜单链接'),
        ),
    ]
