# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-01 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20161201_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(max_length=50, null=True, verbose_name='产品链接'),
        ),
    ]
