# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-16 15:46
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name=b'banner\xe5\x90\x8d\xe7\xa7\xb0')),
                ('images', models.ImageField(upload_to=b'banner', verbose_name=b'banner\xe5\x9b\xbe\xe7\x89\x87')),
            ],
            options={
                'verbose_name': 'banner\u56fe\u7247',
                'verbose_name_plural': 'banner\u56fe\u7247',
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.ImageField(upload_to=b'head', verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7\xe5\xa4\xb4\xe5\x83\x8f')),
                ('name', models.CharField(max_length=20, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7\xe5\x90\x8d')),
                ('context', models.TextField(verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7\xe7\x95\x99\xe8\xa8\x80')),
            ],
            options={
                'verbose_name': '\u5ba2\u6237\u6848\u4f8b',
                'verbose_name_plural': '\u5ba2\u6237\u6848\u4f8b',
            },
        ),
        migrations.CreateModel(
            name='Com_cer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to=b'cer', verbose_name=b'\xe8\xaf\x81\xe4\xb9\xa6')),
            ],
            options={
                'verbose_name_plural': '\u516c\u53f8\u8bc1\u4e66',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name=b'\xe5\x85\xac\xe5\x8f\xb8\xe5\x90\x8d')),
            ],
            options={
                'verbose_name': '\u516c\u53f8\u8bc1\u4e66',
                'verbose_name_plural': '\u516c\u53f8\u8bc1\u4e66',
            },
        ),
        migrations.CreateModel(
            name='Contect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name=b'\xe5\xae\xa2\xe6\x88\xb7\xe5\x90\x8d')),
                ('company', models.CharField(max_length=40, verbose_name=b'\xe5\xae\xa2\xe6\x88\xb7\xe5\x85\xac\xe5\x8f\xb8\xe5\x90\x8d')),
                ('tel', models.IntegerField(verbose_name=b'\xe5\xae\xa2\xe6\x88\xb7\xe7\x94\xb5\xe8\xaf\x9d')),
                ('country', models.CharField(max_length=20, verbose_name=b'\xe6\x89\x80\xe5\x9c\xa8\xe5\x9b\xbd\xe5\xae\xb6')),
                ('email', models.EmailField(max_length=254, verbose_name=b'\xe5\xae\xa2\xe6\x88\xb7\xe9\x82\xae\xe4\xbb\xb6')),
                ('requ', models.TextField(verbose_name=b'\xe5\xae\xa2\xe6\x88\xb7\xe6\x84\x8f\xe8\xa7\x81')),
            ],
            options={
                'verbose_name': '\u5ba2\u6237\u610f\u89c1',
                'verbose_name_plural': '\u5ba2\u6237\u610f\u89c1',
            },
        ),
        migrations.CreateModel(
            name='Exhi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('context', models.TextField(null=True, verbose_name=b'\xe5\xb1\x95\xe4\xbc\x9a\xe5\x86\x85\xe5\xae\xb9')),
            ],
            options={
                'verbose_name': '\u5c55\u4f1a',
                'verbose_name_plural': '\u5c55\u4f1a',
            },
        ),
        migrations.CreateModel(
            name='Exhi_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'exhi', verbose_name=b'\xe5\xb1\x95\xe4\xbc\x9a\xe5\x9b\xbe\xe7\x89\x87')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='en.Exhi')),
            ],
            options={
                'verbose_name_plural': '\u5c55\u4f1a\u56fe\u7247',
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=500, verbose_name=b'\xe9\x97\xae\xe9\xa2\x98')),
                ('answer', models.TextField(max_length=500, verbose_name=b'\xe7\xad\x94\xe6\xa1\x88')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name=b'\xe6\xa0\x87\xe9\xa2\x98')),
                ('context', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name=b'\xe5\x86\x85\xe5\xae\xb9')),
                ('date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u65b0\u95fb',
                'verbose_name_plural': '\u65b0\u95fb',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name=b'\xe4\xba\xa7\xe5\x93\x81\xe5\x90\x8d\xe7\xa7\xb0')),
                ('adver', models.TextField(null=True, verbose_name=b'\xe4\xba\xa7\xe5\x93\x81\xe4\xbc\x98\xe5\x8a\xbf')),
                ('is_index', models.BooleanField(default=1, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe9\xa6\x96\xe9\xa1\xb5\xe5\xb1\x95\xe7\xa4\xba\xe4\xba\xa7\xe5\x93\x81\xe4\xbc\x98\xe5\x8a\xbf')),
                ('image', models.ImageField(upload_to=b'product', verbose_name=b'\xe4\xba\xa7\xe5\x93\x81\xe9\xa6\x96\xe9\xa1\xb5\xe5\xb1\x95\xe7\xa4\xba\xe5\x9b\xbe\xe7\x89\x87')),
                ('context', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name=b'\xe4\xba\xa7\xe5\x93\x81\xe5\x86\x85\xe5\xae\xb9')),
            ],
            options={
                'verbose_name': '\u4ea7\u54c1',
                'verbose_name_plural': '\u4ea7\u54c1',
            },
        ),
        migrations.AddField(
            model_name='com_cer',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='en.Company'),
        ),
    ]
