# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-16 03:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('en', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='products', verbose_name='产品图片')),
            ],
            options={
                'verbose_name_plural': '产品图片',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='img',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.AddField(
            model_name='images',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='en.Product'),
        ),
    ]
