# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-05 06:20
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('en', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index_adv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name=b'\xe9\xa6\x96\xe9\xa1\xb5\xe4\xbc\x98\xe5\x8a\xbf\xe6\xa0\x87\xe9\xa2\x98')),
                ('adv', models.TextField(verbose_name=b'\xe9\xa6\x96\xe9\xa1\xb5\xe4\xbc\x98\xe5\x8a\xbf\xe5\x86\x85\xe5\xae\xb9')),
            ],
            options={
                'default_permissions': 'change',
                'verbose_name': '\u9996\u9875\u4f18\u52bf\u6807\u9898',
                'verbose_name_plural': '\u9996\u9875\u4f18\u52bf\u5185\u5bb9',
            },
        ),
        migrations.CreateModel(
            name='Rece_Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7\xe6\x8f\x90\xe4\xba\xa4\xe7\x9a\x84email\xe5\x9c\xb0\xe5\x9d\x80')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u63d0\u4ea4\u7684email\u5730\u5740',
                'verbose_name_plural': '\u7528\u6237\u63d0\u4ea4\u7684email\u5730\u5740',
            },
        ),
        migrations.AlterModelOptions(
            name='com_info',
            options={'default_permissions': 'change', 'verbose_name': '\u516c\u53f8\u4fe1\u606f', 'verbose_name_plural': '\u516c\u53f8\u4fe1\u606f'},
        ),
        migrations.AlterModelOptions(
            name='contect',
            options={'default_permissions': ('change', 'delete'), 'verbose_name': '\u5ba2\u6237\u610f\u89c1', 'verbose_name_plural': '\u5ba2\u6237\u610f\u89c1'},
        ),
        migrations.RemoveField(
            model_name='advantage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='adver',
        ),
        migrations.AddField(
            model_name='exhi',
            name='image',
            field=models.ImageField(default=b'exhi/1.png', upload_to=b'exhi', verbose_name=b'\xe5\xb0\x81\xe9\x9d\xa2\xe5\x9b\xbe\xe7\x89\x87'),
        ),
        migrations.AlterField(
            model_name='contect',
            name='company',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name=b'\xe5\xae\xa2\xe6\x88\xb7\xe5\x85\xac\xe5\x8f\xb8\xe5\x90\x8d'),
        ),
        migrations.AlterField(
            model_name='contect',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=b'\xe6\x89\x80\xe5\x9c\xa8\xe5\x9b\xbd\xe5\xae\xb6'),
        ),
        migrations.AlterField(
            model_name='contect',
            name='requ',
            field=models.TextField(blank=True, null=True, verbose_name=b'\xe5\xae\xa2\xe6\x88\xb7\xe6\x84\x8f\xe8\xa7\x81'),
        ),
        migrations.AlterField(
            model_name='contect',
            name='tel',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'\xe5\xae\xa2\xe6\x88\xb7\xe7\x94\xb5\xe8\xaf\x9d'),
        ),
        migrations.AlterField(
            model_name='exhi',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='exhi_image',
            name='image',
            field=models.ImageField(upload_to=b'exhi', verbose_name=b'\xe5\xb1\x95\xe4\xbc\x9a\xe5\x9b\xbe\xe7\x89\x87'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=DjangoUeditor.models.UEditorField(blank=True, default=b'u', verbose_name=b'\xe7\xad\x94\xe6\xa1\x88'),
        ),
    ]
