# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-16 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('en', '0002_auto_20161216_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='name',
            field=models.CharField(default='产品图片', max_length=50),
        ),
    ]
