# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-16 03:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('en', '0003_images_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='product',
        ),
        migrations.AlterField(
            model_name='images',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='en.Product'),
        ),
    ]
