# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-16 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('en', '0004_auto_20161216_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(null=True, upload_to='/static/products', verbose_name='产品图片'),
        ),
    ]
