# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-21 04:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('en', '0006_auto_20161216_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.ImageField(upload_to='head', verbose_name='用户头像')),
                ('name', models.CharField(max_length=20, verbose_name='用户名')),
                ('context', models.TextField(verbose_name='用户留言')),
            ],
            options={
                'verbose_name_plural': '客户案例',
            },
        ),
        migrations.CreateModel(
            name='Com_cer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='cer', verbose_name='证书')),
            ],
            options={
                'verbose_name_plural': '公司证书',
            },
        ),
        migrations.CreateModel(
            name='Com_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(verbose_name='公司信息')),
            ],
            options={
                'verbose_name_plural': '公司信息',
            },
        ),
        migrations.CreateModel(
            name='Contect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='客户名')),
                ('company', models.CharField(max_length=40, verbose_name='客户公司名')),
                ('tel', models.IntegerField(verbose_name='客户电话')),
                ('country', models.CharField(max_length=20, verbose_name='所在国家')),
                ('email', models.EmailField(max_length=254, verbose_name='客户邮件')),
                ('requ', models.TextField(verbose_name='客户意见')),
            ],
            options={
                'verbose_name_plural': '客户意见',
            },
        ),
        migrations.CreateModel(
            name='Exhi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('context', models.TextField(verbose_name='展会内容')),
            ],
            options={
                'verbose_name': '展会',
                'verbose_name_plural': '展会',
            },
        ),
        migrations.CreateModel(
            name='Exhi_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='exhi', verbose_name='展会图片')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='en.Exhi')),
            ],
            options={
                'verbose_name_plural': '展会图片',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('context', models.TextField(verbose_name='内容')),
                ('date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻',
            },
        ),
        migrations.CreateModel(
            name='News_Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news', verbose_name='新闻图片')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='en.News')),
            ],
            options={
                'verbose_name_plural': '新闻图片',
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.TextField()),
                ('ans', models.TextField()),
            ],
            options={
                'verbose_name_plural': '科技',
            },
        ),
        migrations.RenameModel(
            old_name='Images',
            new_name='Pro_Images',
        ),
        migrations.RemoveField(
            model_name='product',
            name='url',
        ),
        migrations.AddField(
            model_name='product',
            name='adver',
            field=models.TextField(null=True, verbose_name='产品优势'),
        ),
        migrations.AddField(
            model_name='product',
            name='index',
            field=models.BooleanField(default=False, verbose_name='是否展示首页'),
        ),
        migrations.AddField(
            model_name='com_cer',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='en.Com_info'),
        ),
    ]
