# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-05 09:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('en', '0006_auto_20180305_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advantage',
            name='image',
        ),
    ]
