# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-06 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('en', '0007_remove_advantage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(default=b'', upload_to=b'banner', verbose_name=b'\xe8\x81\x94\xe7\xb3\xbb\xe9\xa1\xb5\xe9\x9d\xa2banner')),
            ],
            options={
                'verbose_name': 'contact\u9875\u9762banner',
            },
        ),
    ]
