# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-07 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('en', '0008_contact_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='contect',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
