# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-21 04:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('en', '0008_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'verbose_name': '客户案例', 'verbose_name_plural': '客户案例'},
        ),
        migrations.AlterModelOptions(
            name='com_info',
            options={'verbose_name': '公司信息', 'verbose_name_plural': '公司信息'},
        ),
        migrations.AlterModelOptions(
            name='contect',
            options={'verbose_name': '客户意见', 'verbose_name_plural': '客户意见'},
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={'verbose_name': '科技', 'verbose_name_plural': '科技'},
        ),
    ]
