# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-07 02:51
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('en', '0009_contect_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=DjangoUeditor.models.UEditorField(blank=True, default=b' ', verbose_name=b'\xe7\xad\x94\xe6\xa1\x88'),
        ),
    ]
