# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-21 07:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('en', '0009_auto_20161221_1239'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Case',
        ),
        migrations.RemoveField(
            model_name='com_cer',
            name='name',
        ),
        migrations.DeleteModel(
            name='Contect',
        ),
        migrations.RemoveField(
            model_name='exhi_image',
            name='name',
        ),
        migrations.RemoveField(
            model_name='news_images',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pro_images',
            name='name',
        ),
        migrations.DeleteModel(
            name='Technology',
        ),
        migrations.DeleteModel(
            name='Com_cer',
        ),
        migrations.DeleteModel(
            name='Com_info',
        ),
        migrations.DeleteModel(
            name='Exhi',
        ),
        migrations.DeleteModel(
            name='Exhi_Image',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='News_Images',
        ),
        migrations.DeleteModel(
            name='Pro_Images',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
