# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-14 14:40
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('en', '0011_auto_20161221_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='context',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='内容'),
        ),
    ]
